// config/courses.js

export const courses = [
  {
    slug: "dca",
    title: "DCA – Diploma in Computer Applications",
    shortTitle: "DCA",
    category: "Computer Applications",
    level: "",
    duration: "12 Months",
    type: "Diploma",
    featured: false,
    thumbnail: "/images/facility-lab.png",
    description:
      "A 12-month diploma covering computer fundamentals, the complete MS Office suite, internet and digital skills, database management with MS Access, HTML & CSS web designing, and graphic designing with CorelDRAW, Photoshop and Canva, culminating in a final practical project and viva.",
    shortDescription:
      "A 12-month diploma covering computer fundamentals, MS Office, internet skills, database, web designing, and graphic designing.",
    highlights: [
      "Computer Fundamentals",
      "MS Word, Excel & PowerPoint",
      "Advanced Excel",
      "Internet & Digital Skills",
      "MS Access",
      "HTML & CSS",
      "CorelDRAW & Photoshop",
      "Canva",
    ],
    skills: [
      "Computer Fundamentals",
      "MS Word",
      "Advanced Excel",
      "PowerPoint",
      "Internet & Digital Skills",
      "MS Access",
      "HTML & CSS",
      "CorelDRAW",
      "Photoshop",
      "Canva",
      "Practical Projects",
    ],
    curriculum: [
      {
        month: 1,
        title: "Computer Fundamentals & Windows",
        topics: [
          "Introduction to computers",
          "Types and generations of computers",
          "Hardware and software",
          "Input and output devices",
          "Memory and storage devices",
          "Operating systems",
          "Windows desktop and settings",
          "Files and folders management",
          "Basic keyboard shortcuts",
        ],
      },
      {
        month: 2,
        title: "MS Word",
        topics: [
          "Creating and editing documents",
          "Text and paragraph formatting",
          "Page setup and printing",
          "Tables, images, shapes and SmartArt",
          "Headers and footers",
          "Mail Merge",
          "Resume, letters and applications",
          "Practical projects",
        ],
      },
      {
        month: 3,
        title: "MS Excel – Basic",
        topics: [
          "Workbook and worksheet",
          "Data entry and formatting",
          "Rows, columns and cells",
          "Basic formulas",
          "SUM, AVERAGE, MIN, MAX, COUNT",
          "Relative and absolute references",
          "Sorting and filtering",
          "Basic charts",
          "Page setup and printing",
        ],
      },
      {
        month: 4,
        title: "MS Excel – Advanced",
        topics: [
          "IF, AND, OR",
          "COUNTIF, SUMIF, AVERAGEIF",
          "VLOOKUP / XLOOKUP",
          "Conditional formatting",
          "Data validation",
          "Advanced charts",
          "Pivot Tables and Pivot Charts",
          "Practical Excel projects",
        ],
      },
      {
        month: 5,
        title: "MS PowerPoint",
        topics: [
          "Creating presentations",
          "Slide layouts and themes",
          "Text and image formatting",
          "Tables and charts",
          "Shapes and SmartArt",
          "Transitions and animations",
          "Audio and video",
          "Slide Master",
          "Presentation techniques",
          "Practical presentation project",
        ],
      },
      {
        month: 6,
        title: "Internet, Email & Digital Skills",
        topics: [
          "Internet fundamentals",
          "Web browsers and search techniques",
          "Email creation and management",
          "Attachments and cloud storage",
          "Google Drive",
          "Google Docs and Sheets",
          "Online forms",
          "Digital payments and online services",
          "Cybersecurity and safe internet practices",
        ],
      },
      {
        month: 7,
        title: "MS Access & Database Management",
        topics: [
          "Introduction to databases",
          "Tables and fields",
          "Creating databases",
          "Data types",
          "Primary keys",
          "Relationships",
          "Queries",
          "Forms",
          "Reports",
          "Practical database project",
        ],
      },
      {
        month: 8,
        title: "HTML & CSS",
        topics: [
          "Introduction to web designing",
          "HTML structure",
          "Headings, paragraphs and lists",
          "Links and images",
          "Tables and forms",
          "HTML5 basics",
          "Introduction to CSS",
          "Colors, fonts and backgrounds",
          "Borders and layouts",
          "Creating a basic website",
        ],
      },
      {
        month: 9,
        title: "CorelDRAW",
        topics: [
          "Introduction to CorelDRAW",
          "Drawing tools",
          "Shapes and objects",
          "Text tools",
          "Color and fills",
          "Outlines",
          "Logo designing",
          "Visiting card designing",
          "Poster and banner designing",
          "Certificate designing",
        ],
      },
      {
        month: 10,
        title: "Adobe Photoshop",
        topics: [
          "Photoshop interface",
          "Layers",
          "Selection tools",
          "Cropping and resizing",
          "Image correction",
          "Text and effects",
          "Background removal",
          "Photo editing",
          "Poster and social-media designs",
          "Practical projects",
        ],
      },
      {
        month: 11,
        title: "Canva & Digital Designing",
        topics: [
          "Canva interface",
          "Templates and layouts",
          "Social media posts",
          "Flyers and brochures",
          "Posters",
          "Presentations",
          "Certificates",
          "Invitations",
          "Basic branding",
          "Digital design projects",
        ],
      },
      {
        month: 12,
        title: "Final Practical Project & Viva",
        topics: [
          "MS Word practical",
          "MS Excel practical",
          "PowerPoint presentation",
          "Database project",
          "Website project",
          "Graphic-design project",
          "Final integrated project",
          "Viva / practical examination",
          "Project submission",
        ],
      },
    ],
    projects: [],
  },

  {
    slug: "adca",
    title: "ADCA – Advanced Diploma in Computer Applications",
    shortTitle: "ADCA",
    category: "Computer Applications",
    level: "Beginner",
    duration: "12 Months",
    type: "Diploma",
    featured: false,
    thumbnail: "/images/facility-lab.png",
    description:
      "A 12-month advanced diploma covering computer fundamentals, MS Office, advanced Excel, basic accounting, Tally Prime with GST, MS Access, HTML & CSS, and graphic designing tools (CorelDRAW, Photoshop, Canva), concluding with a final practical project and examination.",
    shortDescription:
      "A 12-month advanced diploma covering computer applications, MS Office, accounting, Tally Prime with GST, database, web and graphic designing.",
    highlights: [
      "Computer Applications",
      "MS Office & Advanced Excel",
      "Basic Accounting",
      "Tally Prime & GST Basics",
      "Database (MS Access)",
      "Web Designing",
      "Graphic Designing",
    ],
    skills: [
      "Computer Applications",
      "MS Office",
      "Advanced Excel",
      "Accounting",
      "Tally Prime",
      "GST Basics",
      "Database",
      "Web Designing",
      "Graphic Designing",
      "Practical Projects",
    ],
    curriculum: [
      {
        month: 1,
        title: "Computer Fundamentals & Windows",
        topics: [
          "Introduction to computers",
          "Types of computers",
          "Hardware and software",
          "Input and output devices",
          "Memory and storage",
          "Operating systems",
          "Windows interface",
          "Files and folders",
          "Keyboard shortcuts",
          "Basic computer practical",
        ],
      },
      {
        month: 2,
        title: "Typing & MS Word",
        topics: [
          "English typing practice",
          "MS Word interface",
          "Creating and saving documents",
          "Text and paragraph formatting",
          "Page setup",
          "Tables",
          "Pictures, shapes and SmartArt",
          "Headers and footers",
          "Page numbers",
          "Mail Merge",
          "Applications, letters, notices and resume",
        ],
      },
      {
        month: 3,
        title: "MS Excel – Basic",
        topics: [
          "Introduction to Excel",
          "Workbooks and worksheets",
          "Rows, columns and cells",
          "Data entry and formatting",
          "Basic formulas",
          "SUM, AVERAGE, MIN, MAX, COUNT",
          "Cell references",
          "Sorting and filtering",
          "Basic charts",
          "Practical worksheets",
        ],
      },
      {
        month: 4,
        title: "MS Excel – Advanced & Practical",
        topics: [
          "IF, AND and OR",
          "COUNTIF, SUMIF and AVERAGEIF",
          "VLOOKUP/XLOOKUP basics",
          "Conditional formatting",
          "Data validation",
          "Advanced charts",
          "Pivot Tables",
          "Practical projects",
        ],
      },
      {
        month: 5,
        title: "MS PowerPoint, Internet & Email",
        topics: [
          "Creating presentations",
          "Slide layouts and themes",
          "Images, shapes and SmartArt",
          "Tables and charts",
          "Transitions and animations",
          "Internet basics",
          "Web browsers",
          "Search techniques",
          "Email",
          "Attachments",
          "Google Drive",
          "Online forms",
          "Digital safety",
        ],
      },
      {
        month: 6,
        title: "Basic Accounting",
        topics: [
          "Introduction to accounting",
          "Accounting terminology",
          "Assets and liabilities",
          "Capital and drawings",
          "Revenue and expenses",
          "Debit and credit",
          "Golden rules",
          "Journal entries",
          "Ledger",
          "Trial balance",
          "Cash book",
          "Basic Profit & Loss Account",
          "Basic Balance Sheet",
          "Practical exercises",
        ],
      },
      {
        month: 7,
        title: "Tally Prime – Beginner Level",
        topics: [
          "Introduction to Tally Prime",
          "Company creation and alteration",
          "Groups and ledgers",
          "Cash and bank ledgers",
          "Purchase and sales ledgers",
          "Voucher types",
          "Contra, Payment, Receipt, Journal, Purchase and Sales vouchers",
        ],
      },
      {
        month: 8,
        title: "Tally Prime – Practical & GST Basics",
        topics: [
          "Business transaction practice",
          "Purchase and sales entries",
          "Cash and bank transactions",
          "Discount entries",
          "Debit Note and Credit Note",
          "GST introduction",
          "CGST, SGST and IGST",
          "GST ledgers",
          "GST purchase and sales entries",
          "Basic GST reports",
          "Day Book",
          "Trial Balance",
          "Profit & Loss",
          "Balance Sheet",
        ],
      },
      {
        month: 9,
        title: "MS Access & Database",
        topics: [
          "Introduction to databases",
          "Tables",
          "Fields and records",
          "Data types",
          "Primary key",
          "Relationships",
          "Queries",
          "Forms",
          "Reports",
          "Simple database project",
        ],
      },
      {
        month: 10,
        title: "HTML & CSS",
        topics: [
          "Introduction to web designing",
          "HTML structure",
          "Headings and paragraphs",
          "Lists",
          "Links",
          "Images",
          "Tables",
          "Forms",
          "Basic CSS",
          "Colors, fonts, backgrounds and borders",
          "Basic webpage project",
        ],
      },
      {
        month: 11,
        title: "Graphic Designing",
        topics: [
          "CorelDRAW: basic tools, shapes, text, colors, logo, visiting card, poster and banner",
          "Photoshop: interface, layers, selection, cropping, resizing, basic photo editing and background removal",
          "Canva: templates, social media posts, flyers, brochures, certificates and invitations",
        ],
      },
      {
        month: 12,
        title: "Final Practical & Project",
        topics: [
          "MS Word practical",
          "MS Excel practical",
          "PowerPoint presentation",
          "Accounting practical",
          "Tally Prime practical",
          "GST practical",
          "Database project",
          "Website project",
          "Graphic-design project",
          "Final integrated project",
          "Viva",
          "Final practical examination",
        ],
      },
    ],
    projects: [],
  },

  {
    slug: "digital-marketing",
    title: "Digital Marketing – 6-Month Professional Course",
    shortTitle: "Digital Marketing",
    category: "Digital Marketing",
    level: "Beginner to Professional",
    duration: "6 Months",
    type: "Course",
    featured: false,
    thumbnail: "/images/facility-practical.png",
    description:
      "A 6-month professional course covering digital marketing fundamentals, social media marketing, SEO & content marketing, Google Ads, Meta Ads and e-commerce marketing, concluding with a complete practical campaign project, portfolio development and final assessment.",
    shortDescription:
      "A 6-month professional course covering social media marketing, SEO, Google Ads, Meta Ads and e-commerce marketing.",
    highlights: [
      "Social Media Marketing",
      "SEO & Content Marketing",
      "Google Ads",
      "Meta Ads",
      "Email & WhatsApp Marketing",
      "E-Commerce Marketing",
      "Analytics & KPIs",
    ],
    skills: [
      "Digital Marketing Fundamentals",
      "Social Media Marketing",
      "SEO",
      "Content Marketing",
      "Google Ads",
      "Meta Ads",
      "Email Marketing",
      "WhatsApp Marketing",
      "E-Commerce Marketing",
      "Lead Generation",
      "Analytics",
      "Campaign Management",
      "Branding",
      "Digital Strategy",
      "Portfolio Development",
    ],
    curriculum: [
      {
        month: 1,
        title: "Digital Marketing Fundamentals",
        topics: [
          "Introduction to Digital Marketing",
          "Traditional vs Digital Marketing",
          "Digital Marketing ecosystem",
          "Online customer journey",
          "Target audience and buyer persona",
          "Branding fundamentals",
          "Digital marketing strategy",
          "Website and landing-page basics",
          "Introduction to analytics",
          "Practical marketing exercises",
        ],
      },
      {
        month: 2,
        title: "Social Media Marketing",
        topics: [
          "Introduction to Social Media Marketing",
          "Facebook/Instagram marketing",
          "Business page setup and optimization",
          "Content planning",
          "Social-media post creation",
          "Reels and short-video strategy",
          "Hashtags and captions",
          "Content calendar",
          "Audience engagement",
          "Social-media analytics",
          "Practical social-media campaign",
        ],
      },
      {
        month: 3,
        title: "SEO & Content Marketing",
        topics: [
          "Introduction to SEO",
          "Search engines and how they work",
          "Keywords and keyword research",
          "On-page SEO",
          "Off-page SEO basics",
          "Technical SEO fundamentals",
          "Meta titles and descriptions",
          "Website content optimization",
          "Blogging",
          "Content marketing strategy",
          "Local SEO basics",
          "Practical SEO project",
        ],
      },
      {
        month: 4,
        title: "Google Ads & Online Advertising",
        topics: [
          "Introduction to online advertising",
          "Google Ads fundamentals",
          "Search advertising",
          "Display advertising basics",
          "YouTube advertising basics",
          "Campaign structure",
          "Keywords and audience targeting",
          "Ad copywriting",
          "Budget and bidding concepts",
          "Conversion tracking basics",
          "Introduction to remarketing",
          "Practical advertising campaign",
        ],
      },
      {
        month: 5,
        title: "Meta Ads & E-Commerce Marketing",
        topics: [
          "Introduction to Meta Ads",
          "Facebook and Instagram advertising",
          "Campaign objectives",
          "Audience targeting",
          "Custom and lookalike audiences",
          "Ad creatives and copy",
          "Budgeting and optimization",
          "Lead-generation campaigns",
          "E-commerce marketing basics",
          "WhatsApp marketing basics",
          "Email marketing fundamentals",
          "Practical Meta Ads project",
        ],
      },
      {
        month: 6,
        title: "Professional Digital Marketing",
        topics: [
          "Complete digital marketing strategy",
          "SEO campaign planning",
          "Social-media campaign planning",
          "Google Ads campaign",
          "Meta Ads campaign",
          "Content marketing campaign",
          "Lead-generation strategy",
          "Website and landing-page optimization",
          "Google Analytics fundamentals",
          "Performance reports and KPIs",
          "Client/project management",
          "Portfolio development",
          "Complete Digital Marketing practical project",
          "Viva and final practical assessment",
        ],
      },
    ],
    projects: [],
  },

  {
    slug: "graphic-designing",
    title: "Graphic Designing – 6-Month Professional Course",
    shortTitle: "Graphic Designing",
    category: "Graphic Designing",
    level: "Beginner to Professional",
    duration: "6 Months",
    type: "Course",
    featured: false,
    thumbnail: "/images/facility-practical.png",
    description:
      "A 6-month professional course covering the fundamentals of graphic design, CorelDRAW, Adobe Photoshop, Canva, and Adobe InDesign, culminating in a complete branding project, print-ready artwork, portfolio development and final assessment.",
    shortDescription:
      "A 6-month professional course covering design fundamentals, CorelDRAW, Photoshop, Canva and InDesign.",
    highlights: [
      "Design Fundamentals & Colour Theory",
      "CorelDRAW",
      "Adobe Photoshop",
      "Canva",
      "Adobe InDesign & Print Design",
      "Branding & Portfolio",
    ],
    skills: [
      "Graphic Design Fundamentals",
      "CorelDRAW",
      "Photoshop",
      "Canva",
      "InDesign",
      "Logo Design",
      "Photo Editing",
      "Poster Design",
      "Brochure & Flyer Design",
      "Social-Media Design",
      "Branding",
      "Print Design",
      "Typography",
      "Portfolio Development",
    ],
    curriculum: [
      {
        month: 1,
        title: "Fundamentals of Graphic Designing",
        topics: [
          "Introduction to Graphic Designing",
          "Principles of Graphic Design",
          "Elements of Design",
          "Colour Theory",
          "Typography and Fonts",
          "Layout and Composition",
          "Image formats and resolutions",
          "RGB, CMYK and printing basics",
          "Introduction to professional design software",
          "Basic computer and file-management skills",
          "Practical design exercises",
        ],
      },
      {
        month: 2,
        title: "CorelDRAW",
        topics: [
          "Introduction to CorelDRAW",
          "Workspace and tools",
          "Shapes and drawing tools",
          "Text and typography",
          "Colour, fills and outlines",
          "Object alignment and arrangement",
          "Layers and object management",
          "Logo design",
          "Visiting card design",
          "Letterhead design",
          "Certificate design",
          "Practical CorelDRAW projects",
        ],
      },
      {
        month: 3,
        title: "Adobe Photoshop",
        topics: [
          "Introduction to Photoshop",
          "Photoshop interface and tools",
          "Layers and layer management",
          "Selection tools",
          "Cropping and resizing",
          "Image correction and enhancement",
          "Background removal",
          "Photo editing and retouching",
          "Text and effects",
          "Poster and banner design",
          "Social-media post design",
          "Practical Photoshop projects",
        ],
      },
      {
        month: 4,
        title: "Canva & Advanced Designing",
        topics: [
          "Introduction to Canva",
          "Templates and design elements",
          "Social-media graphics",
          "YouTube thumbnails",
          "Posters and promotional designs",
          "Brochures and flyers",
          "Invitations and announcements",
          "Presentation graphics",
          "Brand-kit basics",
          "Combining Canva with CorelDRAW and Photoshop",
          "Practical design assignments",
        ],
      },
      {
        month: 5,
        title: "InDesign & Print Design",
        topics: [
          "Introduction to Adobe InDesign",
          "Page layout and document setup",
          "Text frames and typography",
          "Images and graphics placement",
          "Multi-page document design",
          "Magazine and newsletter design",
          "Brochure and catalogue design",
          "Booklet design",
          "Print-ready file preparation",
          "Bleed, margins and crop marks",
          "Basic printing concepts",
          "Practical InDesign project",
        ],
      },
      {
        month: 6,
        title: "Professional Graphic Design",
        topics: [
          "Complete branding project",
          "Logo and brand identity",
          "Visiting card and letterhead",
          "Brochure/flyer design",
          "Poster and banner design",
          "Social-media campaign design",
          "Photo editing project",
          "Print-ready artwork",
          "Client brief and design workflow",
          "Portfolio development",
          "Complete Graphic Designing practical project",
          "Viva and final practical assessment",
        ],
      },
    ],
    projects: [],
  },

  {
    slug: "spoken-english",
    title: "Spoken English – 6-Month Professional Course",
    shortTitle: "Spoken English",
    category: "Spoken English",
    level: "Professional",
    duration: "6 Months",
    type: "Course",
    featured: false,
    thumbnail: "/images/facility-classroom.png",
    description:
      "A 6-month professional course focused on listening, speaking, reading, writing, grammar, vocabulary and pronunciation, covering advanced grammar, professional speaking, listening and pronunciation skills, reading and vocabulary development, professional writing, and integrated English and professional communication.",
    shortDescription:
      "A 6-month professional course covering grammar, speaking, listening, reading, writing and workplace communication.",
    highlights: [
      "Advanced Grammar",
      "Professional Speaking Skills",
      "Listening & Pronunciation",
      "Reading & Vocabulary",
      "Professional Writing",
      "Interview & Workplace Communication",
    ],
    skills: [
      "Advanced Grammar",
      "Fluent Speaking",
      "Listening Comprehension",
      "Reading Comprehension",
      "Professional Writing",
      "Pronunciation",
      "Vocabulary Development",
      "Public Speaking",
      "Presentation Skills",
      "Group Discussion",
      "Interview Skills",
      "Workplace Communication",
      "Professional English Confidence",
    ],
    curriculum: [
      {
        month: 1,
        title: "Advanced Grammar Foundation",
        topics: [
          "Parts of Speech",
          "Sentence structure and formation",
          "All major Tenses",
          "Articles and Determiners",
          "Prepositions",
          "Conjunctions",
          "Modals and Auxiliary Verbs",
          "Active and Passive Voice",
          "Direct and Indirect Speech",
          "Subject-Verb Agreement",
          "Question formation",
          "Common grammatical errors",
          "Grammar-based exercises",
        ],
      },
      {
        month: 2,
        title: "Professional Speaking Skills",
        topics: [
          "Advanced self-introduction",
          "Everyday and professional conversations",
          "Conversation strategies",
          "Asking and answering questions",
          "Expressing opinions and ideas",
          "Agreeing and disagreeing politely",
          "Making requests and suggestions",
          "Giving instructions",
          "Telephone and online conversations",
          "Role plays and situation-based speaking",
          "Impromptu speaking",
          "Fluency-building activities",
        ],
      },
      {
        month: 3,
        title: "Listening & Pronunciation Skills",
        topics: [
          "Importance of active listening",
          "Listening for main ideas",
          "Listening for specific information",
          "Understanding different accents",
          "Pronunciation fundamentals",
          "Vowel and consonant sounds",
          "Word stress",
          "Sentence stress",
          "Intonation and rhythm",
          "Common pronunciation errors",
          "Listening comprehension exercises",
          "Audio/video-based activities",
        ],
      },
      {
        month: 4,
        title: "Reading & Vocabulary Development",
        topics: [
          "Reading comprehension",
          "Skimming and scanning",
          "Identifying main ideas",
          "Understanding context",
          "Reading newspapers and articles",
          "Professional and academic texts",
          "Vocabulary-building techniques",
          "Synonyms and antonyms",
          "Phrasal verbs",
          "Idioms and commonly used expressions",
          "Collocations",
          "Reading and comprehension exercises",
        ],
      },
      {
        month: 5,
        title: "Professional Writing Skills",
        topics: [
          "Paragraph writing",
          "Essay writing",
          "Formal and informal writing",
          "Email writing",
          "Application and letter writing",
          "Report writing",
          "Notice and announcement writing",
          "Resume/CV writing",
          "Professional correspondence",
          "Summarising and paraphrasing",
          "Grammar and proofreading",
          "Writing practice and assignments",
        ],
      },
      {
        month: 6,
        title: "Integrated English & Professional Communication",
        topics: [
          "Integrated Listening + Speaking activities",
          "Integrated Reading + Writing activities",
          "Group discussions",
          "Debates",
          "Presentations",
          "Public speaking",
          "Interview preparation",
          "Professional workplace communication",
          "Presentation and body-language skills",
          "Vocabulary and grammar revision",
          "Mock interviews",
          "Final speaking, listening, reading and writing assessment",
        ],
      },
    ],
    projects: [],
  },

  {
    slug: "accountancy-tally-prime",
    title: "Accountancy & Tally Prime – 6-Month Professional Course",
    shortTitle: "Tally Prime",
    category: "Accounting",
    level: "Beginner to Professional",
    duration: "6 Months",
    type: "Course",
    featured: false,
    thumbnail: "/images/facility-practical.png",
    description:
      "A 6-month professional course covering the fundamentals of accounting, journal, ledger and final accounts, Tally Prime basics and advanced practical usage, and GST in Tally Prime, concluding with a complete practical company-accounting project and final assessment.",
    shortDescription:
      "A 6-month professional course covering accounting fundamentals, Tally Prime and GST-based practical accounting.",
    highlights: [
      "Accounting Fundamentals",
      "Journal, Ledger & Final Accounts",
      "Tally Prime Basics",
      "Tally Prime Advanced Practical",
      "GST in Tally Prime",
      "Bank Reconciliation & Reports",
    ],
    skills: [
      "Accounting Fundamentals",
      "Journal & Ledger",
      "Final Accounts",
      "Tally Prime",
      "Inventory",
      "GST",
      "Bank Reconciliation",
      "Business Transactions",
      "Financial Reports",
      "Practical Company Accounting",
    ],
    curriculum: [
      {
        month: 1,
        title: "Fundamentals of Accounting",
        topics: [
          "Introduction to Accounting",
          "Objectives and importance of accounting",
          "Accounting terminology",
          "Assets and liabilities",
          "Capital and drawings",
          "Revenue, income and expenses",
          "Debtor and creditor",
          "Debit and credit concepts",
          "Accounting equation",
          "Golden rules of accounting",
          "Types of accounts",
          "Basic accounting transactions",
        ],
      },
      {
        month: 2,
        title: "Journal, Ledger & Final Accounts",
        topics: [
          "Journal entries",
          "Rules of journalising",
          "Compound journal entries",
          "Ledger posting",
          "Cash Book",
          "Petty Cash Book",
          "Purchase Book",
          "Sales Book",
          "Purchase Return",
          "Sales Return",
          "Trial Balance",
          "Rectification of basic errors",
          "Introduction to Final Accounts",
          "Trading Account",
          "Profit & Loss Account",
          "Balance Sheet",
        ],
      },
      {
        month: 3,
        title: "Tally Prime: Basic Concepts",
        topics: [
          "Introduction to Tally Prime",
          "Company creation and alteration",
          "Company features and configuration",
          "Accounting groups",
          "Creation of ledgers",
          "Stock groups and stock items",
          "Units of measurement",
          "Voucher types",
          "Contra entries",
          "Payment entries",
          "Receipt entries",
          "Journal entries",
          "Purchase entries",
          "Sales entries",
          "Practical transaction exercises",
        ],
      },
      {
        month: 4,
        title: "Tally Prime: Advanced Practical",
        topics: [
          "Inventory management",
          "Purchase and sales with inventory",
          "Stock transfer",
          "Credit Note",
          "Debit Note",
          "Discounts",
          "Bank transactions",
          "Bank reconciliation",
          "Cost Centres",
          "Budgets",
          "Outstanding receivables and payables",
          "Day Book",
          "Trial Balance",
          "Profit & Loss",
          "Balance Sheet",
          "Practical business-company project",
        ],
      },
      {
        month: 5,
        title: "GST & Tally Prime",
        topics: [
          "Introduction to GST",
          "GST registration basics",
          "CGST, SGST and IGST",
          "GST rates and tax ledgers",
          "GST configuration in Tally Prime",
          "GST purchase entries",
          "GST sales entries",
          "Input Tax Credit",
          "Reverse Charge basics",
          "Debit/Credit Notes under GST",
          "GST reports",
          "GSTR-1 concepts",
          "GSTR-3B concepts",
          "Practical GST transactions",
          "GST reconciliation basics",
        ],
      },
      {
        month: 6,
        title: "Professional Practical Accounting",
        topics: [
          "Complete business accounting cycle",
          "Company creation",
          "Ledger and inventory setup",
          "Purchase and sales transactions",
          "Cash and bank transactions",
          "GST transactions",
          "Discounts and returns",
          "Bank Reconciliation",
          "Outstanding reports",
          "Stock reports",
          "Trial Balance",
          "Profit & Loss Account",
          "Balance Sheet",
          "GST reports",
          "Final accounts preparation",
          "Complete Tally Prime practical project",
          "Viva and final practical assessment",
        ],
      },
    ],
    projects: [],
  },
];

export function getCourseBySlug(slug) {
  return courses.find((course) => course.slug === slug);
}