import Link from "next/link";
import { ArrowLeft, ExternalLink, FileText } from "lucide-react";
import CertificateDetailActions from "@/components/admin/CertificateDetailActions";
import StatusBadge from "@/components/admin/StatusBadge";
import { getCertificateById, getStudentById } from "@/components/admin/certificateData";
import styles from "@/components/admin/Certificates.module.css";
import documentStyles from "@/components/admin/CertificateDocument.module.css";

export default async function CertificateDetailsPage({ params }) {
  const { id } = await params;
  const certificate = getCertificateById(id);
  const student = certificate ? getStudentById(certificate.studentId) : null;
  if (!certificate || !student) return <div className={styles.empty}><h2>Certificate not found</h2><p>The requested certificate or linked student does not exist in the demo data.</p><Link href="/admin/certificates" className={styles.primaryButton}>Back to certificates</Link></div>;
  const file = certificate.certificateFile;
  return <div><Link href="/admin/certificates" className={styles.backLink}><ArrowLeft size={15} /> Back to certificates</Link><div className={styles.detailHeader}><div><span className={styles.eyebrow}>Verification record</span><h1>Certificate Details</h1><p>Review the certificate and its linked student record.</p></div><CertificateDetailActions certificate={certificate} /></div><section className={styles.hero}><span className={styles.heroMark}>CERT</span><div><h2>{certificate.certificateNumber}</h2><p>{certificate.status}</p></div><div className={styles.heroStatus}><StatusBadge status={certificate.status} /></div></section><div className={styles.detailGrid}><section className={styles.section}><h2>Certificate Information</h2><div className={styles.infoGrid}><div className={styles.infoRow}><label>Certificate Number</label><span className={styles.certificateNumber}>{certificate.certificateNumber}</span></div><div className={styles.infoRow}><label>Status</label><span>{certificate.status}</span></div></div></section><section className={styles.section}><h2>Student Information</h2><div className={styles.infoGrid}><div className={styles.infoRow}><label>Student Name</label><span>{student.fullName}</span></div><div className={styles.infoRow}><label>Enrollment Number</label><span>{student.enrollmentNumber}</span></div><div className={styles.infoRow}><label>Course</label><span>{student.course}</span></div></div></section><section className={styles.section}><h2>Certificate Document</h2>{file ? <div className={documentStyles.documentCard}><FileText size={24} /><div className={documentStyles.documentInfo}><strong>{file.name}</strong><span>{file.type} · {file.size ? `${(file.size / 1024).toFixed(0)} KB` : "Size unavailable"}</span><small>Demo reference only. Permanent storage is not connected.</small></div><button type="button" className={documentStyles.fileAction} disabled={!file.previewUrl}>View Certificate</button></div> : <p className={styles.notes}>No certificate file has been added.</p>}</section><section className={`${styles.section} ${styles.verification}`}><div><h2>Verification Information</h2><p className={styles.notes}>The future verification flow will load student data through this certificate&apos;s student ID.</p><p className={styles.verificationCode}>{certificate.certificateNumber}</p></div><Link href="/verify-certificate" className={styles.secondaryButton}>View Public Verification <ExternalLink size={15} /></Link></section></div></div>;
}
