import Link from "next/link";
import { Eye, FileText, Pencil, RotateCcw, ShieldOff, Trash2 } from "lucide-react";
import StatusBadge from "./StatusBadge";
import styles from "./Certificates.module.css";

export default function CertificateTable({ certificates, onDelete, onToggle }) {
  if (!certificates.length) return <div className={styles.empty}><h2>No certificates found</h2><p>Try changing your search or filters.</p></div>;
  return <><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Certificate Number</th><th>Student</th><th>Course</th><th>Status</th><th>Certificate File</th><th>Actions</th></tr></thead><tbody>{certificates.map((item) => <tr key={item.id}><td className={styles.certificateNumber}>{item.certificateNumber}</td><td><div className={styles.studentCell}><strong>{item.student.fullName}</strong><small>{item.student.enrollmentNumber}</small></div></td><td>{item.student.course}</td><td><StatusBadge status={item.status} /></td><td>{item.certificateFile ? <FileText size={16} aria-label="Certificate file available" /> : <span className={styles.muted}>Not added</span>}</td><td><div className={styles.actions}><Link href={`/admin/certificates/${item.id}`} className={styles.iconButton} aria-label={`View ${item.certificateNumber}`}><Eye size={16} /></Link><Link href={`/admin/certificates/${item.id}/edit`} className={styles.iconButton} aria-label={`Edit ${item.certificateNumber}`}><Pencil size={16} /></Link>{item.status !== "EXPIRED" && <button type="button" className={styles.iconButton} onClick={() => onToggle(item)} aria-label={item.status === "VALID" ? `Revoke ${item.certificateNumber}` : `Restore ${item.certificateNumber}`}>{item.status === "VALID" ? <ShieldOff size={16} /> : <RotateCcw size={16} />}</button>}<button type="button" className={`${styles.iconButton} ${styles.danger}`} onClick={() => onDelete(item)} aria-label={`Delete ${item.certificateNumber}`}><Trash2 size={16} /></button></div></td></tr>)}</tbody></table></div><div className={styles.mobileCards}>{certificates.map((item) => <article className={styles.mobileCard} key={item.id}><div className={styles.mobileCardTop}><span className={styles.certificateNumber}>{item.certificateNumber}</span><StatusBadge status={item.status} /></div><div className={styles.mobileMeta}><span><small>Student</small><strong>{item.student.fullName}</strong></span><span><small>Enrollment</small><strong>{item.student.enrollmentNumber}</strong></span><span><small>Course</small><strong>{item.student.course}</strong></span><span><small>File</small><strong>{item.certificateFile ? "Available" : "Not added"}</strong></span></div><div className={styles.mobileCardActions}><Link href={`/admin/certificates/${item.id}`} className={styles.iconButton}><Eye size={15} /> View</Link><Link href={`/admin/certificates/${item.id}/edit`} className={styles.iconButton}><Pencil size={15} /> Edit</Link>{item.status !== "EXPIRED" && <button type="button" className={styles.iconButton} onClick={() => onToggle(item)}>{item.status === "VALID" ? <ShieldOff size={15} /> : <RotateCcw size={15} />} {item.status === "VALID" ? "Revoke" : "Restore"}</button>}</div></article>)}</div></>;
}
