"use client";

import Link from "next/link";
import { useState } from "react";
import { courseCategories, courseStatuses } from "./courseData";
import styles from "./Courses.module.css";

const initialValues = { name: "", shortCode: "", description: "", duration: "", fees: "", category: "", status: "Active", featured: false, image: "", highlights: "", eligibility: "", curriculum: "" };

export default function CourseForm({ course, submitLabel = "Save Course" }) {
  const [values, setValues] = useState(course ? { ...course, highlights: course.highlights.join("\n"), curriculum: course.curriculum.join("\n") } : initialValues);
  const [errors, setErrors] = useState({});
  const [submitting, setSubmitting] = useState(false);
  const [success, setSuccess] = useState(false);
  const update = (event) => { const { name, value, type, checked } = event.target; setValues((current) => ({ ...current, [name]: type === "checkbox" ? checked : value })); setErrors((current) => ({ ...current, [name]: "" })); setSuccess(false); };
  const submit = (event) => { event.preventDefault(); const nextErrors = {}; ["name", "shortCode", "category", "description", "duration", "fees", "status"].forEach((field) => { if (!String(values[field]).trim()) nextErrors[field] = "This field is required."; }); setErrors(nextErrors); if (Object.keys(nextErrors).length) return; setSubmitting(true); window.setTimeout(() => { setSubmitting(false); setSuccess(true); }, 500); };
  const field = (name, label, type = "text", required = false, placeholder = "") => <div className={styles.field}><label htmlFor={name}>{label} {required && <span className={styles.required}>*</span>}</label><input id={name} name={name} type={type} value={values[name]} onChange={update} placeholder={placeholder} required={required} />{errors[name] && <span className={styles.error}>{errors[name]}</span>}</div>;
  const area = (name, label, required = false, placeholder = "") => <div className={`${styles.field} ${styles.full}`}><label htmlFor={name}>{label} {required && <span className={styles.required}>*</span>}</label><textarea id={name} name={name} value={values[name]} onChange={update} placeholder={placeholder} />{errors[name] && <span className={styles.error}>{errors[name]}</span>}</div>;
  return <form className={styles.form} onSubmit={submit} noValidate>{success && <p className={styles.success} role="status">Course saved in demo mode.</p>}<section className={styles.section}><h2>Basic Information</h2><div className={styles.formGrid}>{field("name", "Course Name", "text", true, "Enter course name")}{field("shortCode", "Short Code", "text", true, "DCA")}{<div className={styles.field}><label htmlFor="category">Category <span className={styles.required}>*</span></label><select id="category" name="category" value={values.category} onChange={update}><option value="">Select category</option>{courseCategories.map((option) => <option key={option}>{option}</option>)}</select>{errors.category && <span className={styles.error}>{errors.category}</span>}</div>}{area("description", "Description", true, "Describe the course for administrators and learners.")}</div></section><section className={styles.section}><h2>Course Details</h2><div className={styles.formGrid}>{field("duration", "Duration", "text", true, "6 months")}{field("fees", "Fees", "text", true, "₹18,000")}{<div className={styles.field}><label htmlFor="status">Status <span className={styles.required}>*</span></label><select id="status" name="status" value={values.status} onChange={update}>{courseStatuses.map((option) => <option key={option}>{option}</option>)}</select></div>}<label className={styles.field}><span>Featured</span><span><input id="featured" name="featured" type="checkbox" checked={values.featured} onChange={update} /> Mark as featured</span></label></div></section><section className={styles.section}><h2>Course Content</h2><div className={styles.formGrid}>{area("highlights", "Course Highlights", false, "One highlight per line")}{area("eligibility", "Eligibility", false, "Who can apply?")}{area("curriculum", "Curriculum", false, "One topic per line")}</div></section><section className={styles.section}><h2>Media</h2><div className={styles.formGrid}>{field("image", "Course Image", "text", false, "/images/courses/course.jpg")}</div></section><div className={styles.formActions}><Link href="/admin/courses" className={styles.secondaryButton}>Cancel</Link><button type="submit" className={styles.primaryButton} disabled={submitting}>{submitting ? "Saving..." : submitLabel}</button></div></form>;
}