import Link from "next/link";
import { Eye, Pencil, Star, Trash2 } from "lucide-react";
import StatusBadge from "./StatusBadge";
import styles from "./Courses.module.css";

function CourseMark({ code }) { return <span className={styles.courseMark}>{code.slice(0, 3)}</span>; }

export default function CourseTable({ courses, onDelete }) {
  if (!courses.length) return <div className={styles.empty}><span className={styles.emptyIcon}><Eye size={21} /></span><h2>No courses found</h2><p>Try changing your search or filters.</p></div>;
  return <><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Course</th><th>Code</th><th>Category</th><th>Duration</th><th>Fees</th><th>Status</th><th>Featured</th><th>Actions</th></tr></thead><tbody>{courses.map((course) => <tr key={course.id}><td><div className={styles.courseCell}><CourseMark code={course.shortCode} /><span><strong>{course.name}</strong><small>{course.description}</small></span></div></td><td className={styles.muted}>{course.shortCode}</td><td>{course.category}</td><td className={styles.muted}>{course.duration}</td><td>{course.fees}</td><td><StatusBadge status={course.status} /></td><td>{course.featured ? <Star size={16} fill="currentColor" color="var(--color-primary)" aria-label="Featured" /> : <span className={styles.muted}>No</span>}</td><td><div className={styles.actions}><Link href={`/admin/courses/${course.id}`} className={styles.iconButton} aria-label={`View ${course.name}`} title="View"><Eye size={16} /></Link><Link href={`/admin/courses/${course.id}/edit`} className={styles.iconButton} aria-label={`Edit ${course.name}`} title="Edit"><Pencil size={16} /></Link><button type="button" className={`${styles.iconButton} ${styles.danger}`} onClick={() => onDelete(course)} aria-label={`Delete ${course.name}`} title="Delete"><Trash2 size={16} /></button></div></td></tr>)}</tbody></table></div><div className={styles.mobileCards}>{courses.map((course) => <article className={styles.mobileCard} key={course.id}><div className={styles.mobileCardTop}><div className={styles.courseCell}><CourseMark code={course.shortCode} /><span><strong>{course.name}</strong><small>{course.shortCode} · {course.category}</small></span></div><StatusBadge status={course.status} /></div><div className={styles.mobileMeta}><span><small>Duration</small><strong>{course.duration}</strong></span><span><small>Fees</small><strong>{course.fees}</strong></span><span><small>Featured</small><strong>{course.featured ? "Yes" : "No"}</strong></span></div><div className={styles.mobileCardActions}><Link href={`/admin/courses/${course.id}`} className={styles.iconButton}><Eye size={15} /> View</Link><Link href={`/admin/courses/${course.id}/edit`} className={styles.iconButton}><Pencil size={15} /> Edit</Link><button type="button" className={`${styles.iconButton} ${styles.danger}`} onClick={() => onDelete(course)}><Trash2 size={15} /> Delete</button></div></article>)}</div></>;
}