import Link from "next/link";
import { Eye, Pencil, Trash2 } from "lucide-react";
import StatusBadge from "./StatusBadge";
import styles from "./Students.module.css";

function Avatar({ name }) { return <span className={styles.avatar}>{name.split(" ").map((part) => part[0]).join("").slice(0, 2)}</span>; }

export default function StudentTable({ students, onDelete }) {
  if (!students.length) return <div className={styles.empty}><span className={styles.emptyIcon}><Eye size={21} /></span><h2>No students found</h2><p>Try changing your search or filters.</p></div>;
  return <>
    <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Student</th><th>Roll Number</th><th>Course</th><th>Phone</th><th>Admission Date</th><th>Status</th><th>Actions</th></tr></thead><tbody>{students.map((student) => <tr key={student._id}><td><div className={styles.studentCell}><Avatar name={student.fullName} /><span><strong>{student.fullName}</strong><small>{student.email}</small></span></div></td><td className={styles.muted}>{student.rollNumber}</td><td>{student.course?.title || "Unknown course"}</td><td className={styles.muted}>{student.phone}</td><td className={styles.muted}>{student.admissionDate?.slice(0, 10)}</td><td><StatusBadge status={student.status} /></td><td><div className={styles.actions}><Link href={`/admin/students/${student._id}`} className={styles.iconButton} aria-label={`View ${student.fullName}`} title="View"><Eye size={16} /></Link><Link href={`/admin/students/${student._id}/edit`} className={styles.iconButton} aria-label={`Edit ${student.fullName}`} title="Edit"><Pencil size={16} /></Link><button type="button" className={`${styles.iconButton} ${styles.danger}`} onClick={() => onDelete(student)} aria-label={`Delete ${student.fullName}`} title="Delete"><Trash2 size={16} /></button></div></td></tr>)}</tbody></table></div>
    <div className={styles.mobileCards}>{students.map((student) => <article className={styles.mobileCard} key={student._id}><div className={styles.mobileCardTop}><div className={styles.studentCell}><Avatar name={student.fullName} /><span><strong>{student.fullName}</strong><small>{student.email}</small></span></div><StatusBadge status={student.status} /></div><div className={styles.mobileMeta}><span><small>Course</small><strong>{student.course?.title || "Unknown course"}</strong></span><span><small>Roll Number</small><strong>{student.rollNumber}</strong></span><span><small>Phone</small><strong>{student.phone}</strong></span><span><small>Admission</small><strong>{student.admissionDate?.slice(0, 10)}</strong></span></div><div className={styles.mobileCardActions}><Link href={`/admin/students/${student._id}`} className={styles.iconButton}><Eye size={15} /> View</Link><Link href={`/admin/students/${student._id}/edit`} className={styles.iconButton}><Pencil size={15} /> Edit</Link><button type="button" className={`${styles.iconButton} ${styles.danger}`} onClick={() => onDelete(student)}><Trash2 size={15} /> Delete</button></div></article>)}</div>
  </>;
}
